language: node.js
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: nathan@cascade-softworks.com
  api_key:
    secure: RRq+Hl9s70V5qcqB4iR+qZIQJhJCeI4jBVK/9MjFe6CaVscPSFMilEsWco2XZSbFmdsAdXq2rczi9AHWYou4X/ut+3PnU0SeWqBkYPd8BF0brZxXPazgX6uuQZ4N3QdXIozk0Naa/X2e1axLRMay5bo9jdHm/0XLjvwtRW5r/i6mzuxP6DmbaYufKxC7BsIsYI02M8J5Weay2TflDcC+V1dHuH/2A7jcqntBEqdAsCzszqsOfsd5uWHmhkv4BcEVpxzrmofCShn4BqLJDCNegdnNE4QO/t2EkONF7pZtPMC1XmRbSl2I5imqBDhYN9WV4hk1nm2L53GRliC6JQMwsbTUWJRAEsXgalgOXk8sbUWfu0Cl8bDMy+RKYl8aa+pbXfLC3BaWOQgZdB0WLeVlTKoTwVFU/SKKxtQVdEqDwjjoo1wbW9vYlpjtWmY5/6r3W/84Sn9L6RbmFwXct6QD6g5naQ2nGcVSkvuu0jAHpQrl3iyU2VMhCf4/G+ag9yRFKNdfyNErAh7odKrJvS2nLEWtP3IAHTtpZ2qlFhpWnajTGFsEFdUXxqR56s3hguNQR848/IgK+/hjt7rOcT6bSd6uDFePURQUAMbhl6i47FMz+VLYKGlkK55syx/Atn/dKZKEXsDkQHuJcj2FRk+HvILY9Jl79r12TFK4VEq4Qxk=
  on:
    tags: true
    repo: nathschmidt/restify-cookies
